# -*- Makefile -*-

lib_TARGETS = champion

# Tu peux rajouter des fichiers sources, headers, ou changer
# des flags de compilation.
champion-srcs = prologin.cc
champion-dists =
champion-cflags = -ggdb3

# Evite de toucher a ce qui suit
champion-dists += prologin.hh
champion-srcs += ../includes/main.c
include ../includes/rules.mk
