
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Caracs__
#define __Caracs__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
    class Caracs;
}

class Caracs : public ::java::lang::Object
{

public: // actually package-private
  Caracs();
public:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) pa_init;
  jint portee;
  static ::java::lang::Class class$;
};

#endif // __Caracs__
