
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Cartes__
#define __Cartes__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
    class Cartes;
}

class Cartes : public ::java::lang::Object
{

public: // actually package-private
  Cartes();
public:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) potion;
  jint deguisement;
  jint banzai;
  jint pacifisme;
  static ::java::lang::Class class$;
};

#endif // __Cartes__
