
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Erreur__
#define __Erreur__

#pragma interface

#include <java/lang/Enum.h>
#include <gcj/array.h>

extern "Java"
{
    class Erreur;
}

class Erreur : public ::java::lang::Enum
{

  Erreur(::java::lang::String *, jint);
public:
  static JArray< ::Erreur * > * values();
  static ::Erreur * valueOf(::java::lang::String *);
  static ::Erreur * Ok;
  static ::Erreur * Position_invalide;
  static ::Erreur * Case_occupee;
  static ::Erreur * Pas_a_portee;
  static ::Erreur * Unite_ko;
  static ::Erreur * Unite_debout;
  static ::Erreur * Quota_depasse;
  static ::Erreur * Plus_de_pa;
  static ::Erreur * Deja_attaque;
  static ::Erreur * Unite_interdite;
  static ::Erreur * Renfort_impossible;
  static ::Erreur * Pas_a_moi;
  static ::Erreur * Plus_de_cartes;
  static ::Erreur * Phase_cartes_terminee;
private:
  static JArray< ::Erreur * > * ENUM$VALUES;
public:
  static ::java::lang::Class class$;
};

#endif // __Erreur__
