
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Interface__
#define __Interface__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
    class Caracs;
    class Cartes;
    class Erreur;
    class Interface;
    class Position;
    class Taille_terrain;
    class Type_unite;
    class Unite;
}

class Interface : public ::java::lang::Object
{

public:
  Interface();
  static jint nombre_pc();
  static jint nombre_unites(jboolean);
  static jint tour_actuel();
  static ::Position * pos_renfort(jboolean);
  static ::Caracs * caracteristiques(::Type_unite *);
  static ::Cartes * mes_cartes();
  static JArray< ::Unite * > * unites();
  static ::Taille_terrain * taille_terrain_actuelle();
  static ::Erreur * potion(::Position *);
  static ::Erreur * deguisement(::Position *, ::Type_unite *);
  static ::Erreur * banzai(::Position *);
  static ::Erreur * pacifisme();
  static ::Erreur * deplacer(::Position *, ::Position *);
  static ::Erreur * relever(::Position *);
  static ::Erreur * attaquer(::Position *, ::Position *);
  static ::Erreur * renfort(::Type_unite *);
  static jboolean annuler();
  static void afficher_erreur(::Erreur *);
  static void afficher_type_unite(::Type_unite *);
  static void afficher_position(::Position *);
  static void afficher_taille_terrain(::Taille_terrain *);
  static void afficher_caracs(::Caracs *);
  static void afficher_unite(::Unite *);
  static void afficher_cartes(::Cartes *);
  static const jint TAILLE_DEPART = 19;
  static const jint NBR_MAX_UNITES = 10;
  static const jint TEMPS_RETRECISSEMENT = 5;
  static const jint MAX_CARTES = 2;
  static ::java::lang::Class class$;
};

#endif // __Interface__
