
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Position__
#define __Position__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
    class Position;
}

class Position : public ::java::lang::Object
{

public: // actually package-private
  Position();
public:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) x;
  jint y;
  static ::java::lang::Class class$;
};

#endif // __Position__
