
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Prologin__
#define __Prologin__

#pragma interface

#include <Interface.h>
extern "Java"
{
    class Position;
    class Prologin;
}

class Prologin : public ::Interface
{

public:
  Prologin();
  virtual void init_game();
  virtual ::Position * retirer_ko();
private:
  void toto();
public:
  virtual void jouer();
  virtual void end_game();
  static ::java::lang::Class class$;
};

#endif // __Prologin__
