
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Taille_terrain__
#define __Taille_terrain__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
    class Taille_terrain;
}

class Taille_terrain : public ::java::lang::Object
{

public: // actually package-private
  Taille_terrain();
public:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) taille;
  jint min_coord;
  jint max_coord;
  static ::java::lang::Class class$;
};

#endif // __Taille_terrain__
