
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Type_unite__
#define __Type_unite__

#pragma interface

#include <java/lang/Enum.h>
#include <gcj/array.h>

extern "Java"
{
    class Type_unite;
}

class Type_unite : public ::java::lang::Enum
{

  Type_unite(::java::lang::String *, jint);
public:
  static JArray< ::Type_unite * > * values();
  static ::Type_unite * valueOf(::java::lang::String *);
  static ::Type_unite * Perroquet;
  static ::Type_unite * Singe;
  static ::Type_unite * Chat;
  static ::Type_unite * Kangourou;
private:
  static JArray< ::Type_unite * > * ENUM$VALUES;
public:
  static ::java::lang::Class class$;
};

#endif // __Type_unite__
